// Stable operation IDs are a compatibility assertion, not generated from the manifest.
// Method/path coverage and permissions are separately parsed from the source spec.
export const expectedOperationIds = new Map(
  `
GET /health checkLiveness
GET /health/ready checkReadiness
GET /app/config getAppConfig
GET /app/bootstrap bootstrapApp
GET /home getHomeFeed
GET /onboarding/status getOnboardingStatus
PUT /onboarding updateOnboarding
POST /onboarding/complete completeOnboarding
POST /auth/sync syncAuth
GET /auth/me getMe
POST /auth/fcm-tokens addFcmToken
DELETE /auth/fcm-tokens/:tokenId removeFcmToken
GET /users/me getMyProfileSummary
PATCH /users/me updateMyProfile
DELETE /users/me deleteMyAccount
GET /users/:userId/public getPublicUserProfile
GET /users/me/content getMyContent
GET /users/me/activity getMyActivity
GET /profiles/me getMyFullProfile
PUT /profiles/me upsertMyProfile
GET /nutrition-profiles/me getMyNutritionProfile
PUT /nutrition-profiles/me upsertMyNutritionProfile
POST /nutrition-profiles/me/recalculate recalculateNutritionTarget
GET /categories getCategories
POST /categories createCategory
PATCH /categories/:id updateCategory
DELETE /categories/:id deleteCategory
GET /allergens getAllergens
POST /allergens createAllergen
PATCH /allergens/:id updateAllergen
DELETE /allergens/:id deleteAllergen
GET /food-items searchFoodItems
GET /food-items/:id getFoodItem
POST /food-items createFoodItem
PATCH /food-items/:id updateFoodItem
DELETE /food-items/:id deleteFoodItem
GET /recipes getRecipes
GET /recipes/mine getMyRecipes
GET /recipes/:idOrSlug getRecipe
POST /recipes createRecipe
PATCH /recipes/:id updateRecipe
DELETE /recipes/:id deleteRecipe
POST /recipes/:id/submit submitRecipe
POST /recipes/:id/publish publishRecipe
POST /recipes/:id/reject rejectRecipe
GET /recipes/:id/nutrition getRecipeNutrition
GET /search searchContent
GET /search/suggestions getSearchSuggestions
GET /search/recent getRecentSearches
DELETE /search/recent clearRecentSearches
DELETE /search/recent/:id deleteRecentSearch
GET /discover discoverContent
GET /recommendations/recipes getRecipeRecommendations
GET /recommendations/content getContentRecommendations
GET /pantry getPantry
POST /pantry/items addPantryItem
POST /pantry/items/bulk addPantryItemsBulk
PATCH /pantry/items/:itemId updatePantryItem
DELETE /pantry/items/:itemId deletePantryItem
GET /pantry/expiring getExpiringPantryItems
GET /pantry/recipe-suggestions getPantryRecipeSuggestions
GET /meal-plans getMealPlans
GET /meal-plans/current getCurrentMealPlan
GET /meal-plans/:id getMealPlan
POST /meal-plans createMealPlan
PATCH /meal-plans/:id updateMealPlan
DELETE /meal-plans/:id deleteMealPlan
POST /meal-plans/:id/meals addMealToPlan
PATCH /meal-plans/:id/meals/:mealId updateMealInPlan
DELETE /meal-plans/:id/meals/:mealId deleteMealFromPlan
POST /meal-plans/:id/activate activateMealPlan
POST /meal-plans/:id/clone cloneMealPlan
POST /meal-plans/:id/grocery-list generateGroceryListFromPlan
GET /grocery-lists getGroceryLists
GET /grocery-lists/:id getGroceryList
POST /grocery-lists createGroceryList
PATCH /grocery-lists/:id updateGroceryList
DELETE /grocery-lists/:id deleteGroceryList
POST /grocery-lists/:id/items addGroceryItem
PATCH /grocery-lists/:id/items/:itemId updateGroceryItem
DELETE /grocery-lists/:id/items/:itemId deleteGroceryItem
POST /grocery-lists/:id/clear-checked clearCheckedGroceryItems
GET /diary getDiaryEntries
POST /diary createDiaryEntry
PATCH /diary/:id updateDiaryEntry
DELETE /diary/:id deleteDiaryEntry
GET /diary/summary getDiarySummary
GET /weight-logs getWeightLogs
POST /weight-logs createWeightLog
PATCH /weight-logs/:id updateWeightLog
DELETE /weight-logs/:id deleteWeightLog
GET /weight-logs/trend getWeightTrend
GET /water-logs getWaterLogs
POST /water-logs createWaterLog
PATCH /water-logs/:id updateWaterLog
DELETE /water-logs/:id deleteWaterLog
POST /media/upload-requests createUploadRequest
GET /media/mine getMyMedia
POST /media/:id/confirm confirmMediaUpload
GET /media/:id getMediaAsset
DELETE /media/:id deleteMediaAsset
GET /posts getPosts
GET /posts/mine getMyPosts
GET /posts/:id getPost
POST /posts createPost
PATCH /posts/:id updatePost
DELETE /posts/:id deletePost
POST /posts/:id/submit submitPost
POST /posts/:id/publish publishPost
POST /posts/:id/reject rejectPost
GET /comments getComments
POST /comments createComment
PATCH /comments/:id updateComment
DELETE /comments/:id deleteComment
PUT /reactions/:targetType/:targetId upsertReaction
DELETE /reactions/:targetType/:targetId deleteReaction
GET /saved-items getSavedItems
PUT /saved-items/:targetType/:targetId saveItem
DELETE /saved-items/:targetType/:targetId unsaveItem
GET /ai/conversations getAiConversations
POST /ai/conversations createAiConversation
GET /ai/conversations/:id/messages getAiMessages
POST /ai/conversations/:id/messages sendAiMessage
POST /ai/meal-plan-proposals createMealPlanProposal
POST /ai/meal-plan-proposals/:proposalId/confirm confirmMealPlanProposal
POST /ai/ingredient-recognition recognizeIngredients
POST /ai/pantry-proposals/:proposalId/confirm confirmPantryProposal
POST /ai/video-summaries generateVideoSummary
PUT /ai/runs/:runId/feedback submitAiFeedback
GET /notifications getNotifications
GET /notifications/unread-count getUnreadNotificationCount
PATCH /notifications/:id/read markNotificationAsRead
POST /notifications/read-all markAllNotificationsAsRead
DELETE /notifications/:id deleteNotification
GET /notification-preferences getNotificationPreferences
PUT /notification-preferences upsertNotificationPreferences
GET /reminders getReminders
POST /reminders createReminder
PATCH /reminders/:id updateReminder
DELETE /reminders/:id deleteReminder
POST /reports createReport
GET /reports/mine getMyReports
GET /reports/mine/:id getMyReport
GET /admin/reports getAdminReports
PATCH /admin/reports/:id updateAdminReport
GET /admin/moderation-cases getModerationCases
POST /admin/moderation-cases createModerationCase
PATCH /admin/moderation-cases/:id updateModerationCase
POST /admin/moderation/:targetType/:targetId/hide hideContent
POST /admin/moderation/:targetType/:targetId/restore restoreContent
POST /admin/users/:id/suspend suspendUser
POST /admin/users/:id/activate activateUser
GET /admin/users getAdminUsers
GET /admin/audit-logs getAuditLogs
GET /videos getVideos
GET /videos/mine getMyVideos
GET /videos/:idOrSlug getVideo
POST /videos createVideo
PATCH /videos/:id updateVideo
DELETE /videos/:id deleteVideo
POST /videos/:id/submit submitVideo
POST /videos/:id/publish publishVideo
POST /videos/:id/reject rejectVideo
GET /videos/:id/related getRelatedVideos
PUT /videos/:id/progress updateVideoProgress
GET /videos/:id/transcript getVideoTranscript
POST /videos/:id/generate-summary generateVideoSummaryFromVideoId
PUT /ratings/:targetType/:targetId upsertRating
DELETE /ratings/:targetType/:targetId deleteRating
GET /ratings/:targetType/:targetId/summary getRatingSummary
GET /view-history getViewHistory
DELETE /view-history clearViewHistory
DELETE /view-history/:targetType/:targetId deleteViewHistoryItem
PUT /view-history/:targetType/:targetId recordView
GET /admin/dashboard/summary getDashboardSummary
GET /admin/dashboard/content-trends getContentTrends
GET /admin/dashboard/user-trends getUserTrends
GET /admin/content/pending getPendingContent
GET /admin/users/:id getAdminUserDetail
PATCH /admin/users/:id/role changeUserRole
GET /admin/ai/runs getAiRuns
GET /admin/ai/runs/:id getAiRunDetail
GET /admin/ai/metrics getAiMetrics
GET /admin/ai/feedback getAiFeedback
`
    .trim()
    .split("\n")
    .map((line) => {
      const [method, path, operationId] = line.split(" ");
      return [`${method} ${path}`, operationId];
    }),
);
