export const contentCardProjection = Object.fromEntries(
  [
    "_id",
    "slug",
    "title",
    "description",
    "excerpt",
    "coverImageUrl",
    "coverMediaId",
    "thumbnailMediaId",
    "categoryIds",
    "tags",
    "allergenIds",
    "difficulty",
    "totalMinutes",
    "nutritionPerServing",
    "publishedAt",
    "createdAt",
    "authorId",
    "ratingAverage",
    "ratingCount",
    "viewCount",
    "durationSeconds",
    "status",
    "visibility",
    "deletedAt",
  ].map((key) => [key, 1]),
);
export const foodCardProjection = Object.fromEntries(
  [
    "_id",
    "name",
    "slug",
    "imageUrl",
    "categoryId",
    "allergenIds",
    "isVegan",
    "isVegetarian",
    "nutritionPer100g",
    "createdAt",
  ].map((key) => [key, 1]),
);
